
import React, { useState, useEffect } from 'react';
import SearchBar from './SearchBar';
import { supabase, getAuthHeader } from '@/lib/supabase';
import { Skeleton } from '@/components/ui/skeleton';

const Hero: React.FC = () => {
  const [welcomeMessage, setWelcomeMessage] = useState<string>('');
  const [isLoadingMessage, setIsLoadingMessage] = useState<boolean>(true);
  const [geminiInfo, setGeminiInfo] = useState<string>('');

  useEffect(() => {
    const fetchWelcomeMessage = async () => {
      try {
        const { data, error } = await supabase.functions.invoke('get-welcome-message', {
          headers: getAuthHeader()
        });
        
        if (error) {
          console.error('Error fetching welcome message:', error);
          setWelcomeMessage('Discover the perfect AI tools tailored to your specific needs and workflows.');
        } else {
          setWelcomeMessage(data.message || 'Find AI tools that transform how you work');
          
          // Set Gemini info if available
          if (data.source) {
            setGeminiInfo(`Message generated by Google Gemini - ${new Date().toLocaleDateString()}`);
          }
        }
      } catch (err) {
        console.error('Exception fetching welcome message:', err);
        setWelcomeMessage('Discover the perfect AI tools tailored to your specific needs and workflows.');
      } finally {
        setIsLoadingMessage(false);
      }
    };

    fetchWelcomeMessage();
  }, []);

  return (
    <section className="relative overflow-hidden pt-20 pb-16 md:pt-32 md:pb-24">
      {/* Background decoration - subtle gradient overlay */}
      <div className="absolute inset-0 bg-gradient-to-b from-blue-50/50 to-transparent pointer-events-none" />
      
      {/* Decorative circles */}
      <div className="absolute -top-24 -right-24 w-96 h-96 rounded-full bg-primary/5 filter blur-3xl opacity-70 animate-float" />
      <div className="absolute -bottom-24 -left-24 w-80 h-80 rounded-full bg-primary/10 filter blur-3xl opacity-60 animate-float" style={{ animationDelay: '1s' }} />
      
      <div className="container mx-auto px-4 relative z-10">
        <div className="max-w-3xl mx-auto text-center">
          <div className="mb-2 inline-block px-3 py-1 bg-primary/10 text-primary rounded-full text-xs font-medium tracking-wide animate-fade-in">
            Discover the perfect AI tools for your tasks
          </div>
          
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6 animate-scale-in">
            Find the <span className="text-gradient">AI tools</span> that elevate your workflow
          </h1>
          
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto animate-slide-up">
            {isLoadingMessage ? (
              <Skeleton className="h-6 w-full mx-auto" />
            ) : (
              welcomeMessage
            )}
          </p>
          
          {geminiInfo && (
            <div className="mb-4 text-xs text-gray-400 animate-fade-in flex items-center justify-center">
              <svg className="w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm.5-13h-1v6l5.25 3.15.75-1.23-5-3.03z" />
              </svg>
              {geminiInfo}
            </div>
          )}
          
          <div className="animate-fade-in" style={{ animationDelay: '0.2s' }}>
            <SearchBar />
          </div>
          
          <div className="mt-8 text-gray-500 text-sm animate-fade-in" style={{ animationDelay: '0.4s' }}>
            Try: "I need to transcribe and summarize podcast episodes" or "Design a logo for my startup"
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
