// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnycgfzpfoiuwwnhxtjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueWNnZnpwZm9pdXd3bmh4dGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4Mjc4MTQsImV4cCI6MjA1NjQwMzgxNH0.FnSsLndEpMA0CkI-u-_7jXP6NxAsj4yXn3Ft-NqqdBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);